# Generated by Django 3.1.6 on 2022-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_cart_cartproduct_category_order_product_productview_review_slider_trendingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
