# Generated by Django 3.1.6 on 2022-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_prof_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('prof_image', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
        ),
    ]
